# Generated by Django 4.1.7 on 2024-01-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_image_shop_shop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('modal_no', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.FloatField(null=True)),
                ('quantity', models.CharField(max_length=30)),
                ('price_in_kg', models.IntegerField(default=0, max_length=1)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
