# Generated by Django 4.1.7 on 2024-01-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_in_kg',
        ),
        migrations.AddField(
            model_name='item',
            name='price_type',
            field=models.IntegerField(choices=[('FOR 1 KG', 'FOR 1 KG'), ('FOR 1 LTR', 'FOR 1 LTR'), ('PER PIECE', 'PER PIECE')], default='PER PIECE'),
        ),
    ]
