# Generated by Django 4.1.7 on 2024-01-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_item_price_in_kg_item_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_type',
            field=models.CharField(choices=[('FOR 1 KG', 'FOR 1 KG'), ('FOR 1 LTR', 'FOR 1 LTR'), ('PER PIECE', 'PER PIECE')], default='PER PIECE', max_length=20),
        ),
    ]
