# Generated by Django 4.1.7 on 2024-01-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_item_price_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_type',
        ),
    ]
