# Generated by Django 5.0 on 2024-01-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='image',
            new_name='shop_image',
        ),
    ]
