# Generated by Django 4.1.7 on 2024-01-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_image_shop_shop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=50)),
                ('price_type', models.CharField(choices=[('FOR 1 KG', 'FOR 1 KG'), ('FOR 1 LTR', 'FOR 1 LTR'), ('PER PIECE', 'PER PIECE')], default='PER PIECE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=30, null=True)),
                ('modal_no', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.FloatField(null=True)),
                ('quantity', models.CharField(max_length=30)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Item_Category', models.ForeignKey(on_delete=models.SET('NONE'), to='shop.item_category')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
